# Generated by Django 6.0 on 2026-06-10 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان تخصص")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, unique=True, verbose_name="متن جایگزین"
                    ),
                ),
            ],
            options={
                "verbose_name": "تخصص",
                "verbose_name_plural": "تخصص\u200cها",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="نام کامل"),
                ),
                (
                    "national_id",
                    models.CharField(max_length=10, unique=True, verbose_name="کد ملی"),
                ),
                ("birth_date", models.DateField(verbose_name="تاریخ تولد")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "مرد"), ("female", "زن"), ("other", "سایر")],
                        max_length=10,
                        verbose_name="جنسیت",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "پروفایل بیمار",
                "verbose_name_plural": "پروفایل بیماران",
            },
        ),
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="نام کامل"),
                ),
                (
                    "medical_license_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="شماره نظام پزشکی"
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="بیوگرافی")),
                ("clinic_address", models.TextField(verbose_name="آدرس کلینیک")),
                (
                    "price",
                    models.PositiveIntegerField(verbose_name="هزینه نوبت (تومان)"),
                ),
                (
                    "rating_avg",
                    models.FloatField(default=0.0, verbose_name="میانگین امتیاز"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doctors",
                        to="accounts.specialty",
                        verbose_name="تخصص",
                    ),
                ),
            ],
            options={
                "verbose_name": "پروفایل پزشک",
                "verbose_name_plural": "پروفایل پزشکان",
            },
        ),
    ]
