# Generated by Django 6.0 on 2026-06-22 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_specialty_patientprofile_doctorprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctorprofile",
            options={
                "verbose_name": "Doctor Profile",
                "verbose_name_plural": "Doctors Profile",
            },
        ),
        migrations.AlterModelOptions(
            name="patientprofile",
            options={
                "verbose_name": "Patient Profile",
                "verbose_name_plural": "Patients Profile",
            },
        ),
        migrations.AlterModelOptions(
            name="specialty",
            options={
                "ordering": ["title"],
                "verbose_name": "specialty",
                "verbose_name_plural": "specialties",
            },
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="specialty",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="If you don't enter anything in this field, it will automatically fill it in.",
                unique=True,
                verbose_name="متن جایگزین",
            ),
        ),
    ]
