# Generated by Django 6.0.6 on 2026-07-04 19:19

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=20, region=None, unique=True
            ),
        ),
    ]
