# Generated by Django 6.0 on 2026-06-22 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_alter_doctorprofile_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ")),
                ("start_time", models.TimeField(verbose_name="ساعت شروع")),
                ("end_time", models.TimeField(verbose_name="ساعت پایان")),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="قابل رزرو"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slots",
                        to="accounts.doctorprofile",
                        verbose_name="پزشک",
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Slot",
                "verbose_name_plural": "Time Slots",
                "ordering": ["date", "start_time"],
                "unique_together": {("doctor", "date", "start_time")},
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار تایید"),
                            ("confirmed", "تایید شده"),
                            ("cancelled", "لغو شده"),
                            ("completed", "انجام شده"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="یادداشت")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="accounts.doctorprofile",
                        verbose_name="پزشک",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="accounts.patientprofile",
                        verbose_name="بیمار",
                    ),
                ),
                (
                    "time_slot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment",
                        to="appointments.timeslot",
                        verbose_name="ساعت نوبت",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
                "ordering": ["-created_at"],
            },
        ),
    ]
